/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prueba_hackerman.newpackage;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.JTextField;
import  javax.swing.Timer;

/**
 *
 * @author canod
 */
public class JugadorEncuentra extends javax.swing.JFrame {
    int Secreto = (int) (Math.random() * 100) + 1;
    int Oportunides = 10;
    Timer time; 

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JugadorEncuentra.class.getName());

    /**
     * Creates new form JugadorEncuentra
     */
    public JugadorEncuentra() {
        initComponents();
        //aqui se crea de manera formal un timer que estara contando cada segundo 
        //de manera en la que cuando el contador llegue a 60 el usuario pierda
        //se agrega 1000 milisegundos de conteo y el action listener para ser el 
        //encargado de poder avisar cada que pasa un segundo y dentro del metodo 
        // se crea una variabler que es la encargada de avisarque el contador a llegado a 60
        time = new Timer(1000, new ActionListener() {
            int Contador = 50;
            public void actionPerformed(ActionEvent e) {
                Contador--;
                
                SalidaContador.setText("ALERTA: RASTREO DEL SISTEMA EN "+Contador);
                SalidaContador.setForeground(Color.GREEN);
                
                if (Contador <=0){
                    time.stop();
                    SalidaContador.setText("|RASTREADO|");
                    SalidaContador.setForeground(Color.red);
                    Ejecutar1.setEnabled(false);
                    
                }
            }
        });
        //Aqui se configuran de que manera se muestran las cajas de texto 
        //Primero se bloquean para que el usuario no borre o intente 
        //ingresar informacion desde ahi
        Pistas.setEditable(false);
        SalidaOportunidades1.setEditable(false);  
        SalidaContador.setEditable(false);
        
        //Se centran los textos para una mejor visualizacion
        Pistas.setHorizontalAlignment(JTextField.CENTER);
        SalidaOportunidades1.setHorizontalAlignment(JTextField.CENTER);
        SalidaContador.setHorizontalAlignment(JTextField.CENTER);
        
    }

    public void JugadorEnc() {
        //se inicia el timer de cuenta regresiva
        time.start();
        //se reciben los datos ingresados por el usuario en la la variable a 
        //tambien se empieza el contador de oportunidades para el usuario
        //que se creo en la clase principal y desde aqui se va restando 
        //cada oportunidad gastada
        try {
            int A = Integer.parseInt(EntradaNumero.getText());
            SalidaOportunidades1.setText("OPORTUNIDAD: " + Oportunides + " INTENTOS RESTANTES:" + (Oportunides - 1) + " ");
            Oportunides--;
            if (A < Secreto) {
                Pistas.setText("EL NUMERO DEBE DE SER MAYOR");
            } else if (A > Secreto) {
                Pistas.setText("EL NUMERO DEBE DE SER MENOR");
            } else if (A == Secreto) {
                Pistas.setText("ACCESO AUTORIZADO");
                time.stop();
            }
            if (Oportunides <= 0) {
                Pistas.setText("SIN INTENTOS DISPONIBLES");
                time.stop();
                Pistas.setForeground(Color.red);
                Ejecutar1.setEnabled(false);
            }
            //Aqui se hace la forma para detectar errores por ejemplo
            //una linea vacia o letras ingresadas por error 
        } catch (NumberFormatException e) {
            time.stop();
            Pistas.setText("ERROR: INGRESA NÚMEROS");
            Pistas.setForeground(Color.ORANGE);
            EntradaNumero.setText("");

        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Back = new javax.swing.JButton();
        SalidaContador = new javax.swing.JTextField();
        Pistas = new javax.swing.JTextField();
        Ejecutar1 = new javax.swing.JButton();
        EntradaNumero = new javax.swing.JTextField();
        SalidaOportunidades1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Back.setBackground(new java.awt.Color(0, 0, 0));
        Back.setFont(new java.awt.Font("VT323", 3, 36)); // NOI18N
        Back.setForeground(new java.awt.Color(51, 255, 51));
        Back.setText("R E G R E S A R");
        Back.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51)));
        Back.addActionListener(this::BackActionPerformed);
        jPanel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 550, 260, 60));

        SalidaContador.setBackground(new java.awt.Color(0, 0, 0));
        SalidaContador.setFont(new java.awt.Font("VT323", 0, 24)); // NOI18N
        SalidaContador.setForeground(new java.awt.Color(0, 255, 0));
        SalidaContador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SalidaContador.addActionListener(this::SalidaContadorActionPerformed);
        jPanel1.add(SalidaContador, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 117, 360, 40));

        Pistas.setBackground(new java.awt.Color(0, 0, 0));
        Pistas.setFont(new java.awt.Font("VT323", 0, 36)); // NOI18N
        Pistas.setForeground(new java.awt.Color(0, 255, 0));
        Pistas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));
        jPanel1.add(Pistas, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 440, 60));

        Ejecutar1.setBackground(new java.awt.Color(0, 0, 0));
        Ejecutar1.setFont(new java.awt.Font("VT323", 0, 24)); // NOI18N
        Ejecutar1.setForeground(new java.awt.Color(51, 255, 51));
        Ejecutar1.setText("I N T E N T A R");
        Ejecutar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51)));
        Ejecutar1.addActionListener(this::Ejecutar1ActionPerformed);
        jPanel1.add(Ejecutar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, 260, 60));

        EntradaNumero.setBackground(new java.awt.Color(0, 0, 0));
        EntradaNumero.setFont(new java.awt.Font("VT323", 0, 36)); // NOI18N
        EntradaNumero.setForeground(new java.awt.Color(0, 255, 0));
        EntradaNumero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));
        jPanel1.add(EntradaNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 510, 60));

        SalidaOportunidades1.setBackground(new java.awt.Color(0, 0, 0));
        SalidaOportunidades1.setFont(new java.awt.Font("VT323", 0, 36)); // NOI18N
        SalidaOportunidades1.setForeground(new java.awt.Color(0, 255, 0));
        SalidaOportunidades1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));
        jPanel1.add(SalidaOportunidades1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 840, 90));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("VT323", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 51));
        jLabel2.setText("MAXIMO 10 INTENTOS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenn/Captura de pantalla 2026-03-18 144810.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 0, -1, 666));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
         Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void Ejecutar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ejecutar1ActionPerformed
       JugadorEnc();
    }//GEN-LAST:event_Ejecutar1ActionPerformed

    private void SalidaContadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalidaContadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalidaContadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JugadorEncuentra().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Ejecutar1;
    private javax.swing.JTextField EntradaNumero;
    private javax.swing.JTextField Pistas;
    private javax.swing.JTextField SalidaContador;
    private javax.swing.JTextField SalidaOportunidades1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
