/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prueba_hackerman.newpackage;
import java.awt.Color;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.io.InputStream;
import java.awt.FontFormatException;
import java.io.IOException;

/**
 *
 * @author Damian
 */
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SalirBtn = new javax.swing.JButton();
        JugadorAdivina = new javax.swing.JButton();
        PcEncuentra = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(13, 13, 13));
        jPanel1.setForeground(new java.awt.Color(13, 13, 13));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SalirBtn.setBackground(new java.awt.Color(0, 0, 0));
        SalirBtn.setFont(new java.awt.Font("VT323", 0, 14)); // NOI18N
        SalirBtn.setForeground(new java.awt.Color(255, 0, 0));
        SalirBtn.setText("CERRAR JUEGO");
        SalirBtn.addActionListener(this::SalirBtnActionPerformed);
        jPanel1.add(SalirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 590, 190, 30));

        JugadorAdivina.setBackground(new java.awt.Color(0, 0, 0));
        JugadorAdivina.setFont(new java.awt.Font("VT323", 0, 14)); // NOI18N
        JugadorAdivina.setForeground(new java.awt.Color(102, 255, 51));
        JugadorAdivina.setText("JUGADOR ADIVINA");
        JugadorAdivina.addActionListener(this::JugadorAdivinaActionPerformed);
        jPanel1.add(JugadorAdivina, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 590, 190, 30));

        PcEncuentra.setBackground(new java.awt.Color(0, 0, 0));
        PcEncuentra.setFont(new java.awt.Font("VT323", 0, 14)); // NOI18N
        PcEncuentra.setForeground(new java.awt.Color(102, 255, 51));
        PcEncuentra.setText("PC ENCUENTRA");
        PcEncuentra.addActionListener(this::PcEncuentraActionPerformed);
        jPanel1.add(PcEncuentra, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 590, 190, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenn/imagenhacker1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1231, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PcEncuentraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PcEncuentraActionPerformed
        PcEncuentra ventana = new PcEncuentra();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PcEncuentraActionPerformed

    private void SalirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirBtnActionPerformed

    private void JugadorAdivinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugadorAdivinaActionPerformed
        MenuDificultades menuDificultades = new MenuDificultades();
        menuDificultades.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_JugadorAdivinaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JugadorAdivina;
    private javax.swing.JButton PcEncuentra;
    private javax.swing.JButton SalirBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
